### ISSUE TITLE
Exercise 5.10 lacking instructions

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#100]
Exercise 5.10 is "Tune first_byte_timeout".

The instructions just say set first_byte_timeout to 1 second and check how varnish times out. At no point do they refer to actually hitting a page that takes longer than 1 second to generate -- or how to generate that page. This is in the solution of course, but it would be much better if that was part of the instructions.

**Comment by Dridi** [comment]
What used to be instructions now lives in the solution space, it could be reverted as part of #103.

**Comment by franciscovg** [comment]
Instructions added in 3e8b38e.
