### ISSUE TITLE
Make "Configure Varnish" an exercise

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#101]
3.4 looks like it actually is an exercise, it just isn't labeled as one. It even contains instructions :) I'm guessing it just needs to be labeled as such?

If it's not intended to be an exercise, then it would probably be a good idea to think about making it one.

**Comment by Dridi** [comment]
It used to be an exercise, and I believe that @franciscovg turned it back into an exercise after we discussed it. We may have forgotten the label indeed :)

**Comment by franciscovg** [comment]
Done in ddf20a3.  This reads now as an exercise that gives step by step instructions.
