### ISSUE TITLE
Compression chapter lacking important information

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#102]
Section 10.7, Compression.

The section says what we have to make a decision about compression for good reasons, but it is lacking instructions for how to actually do that (with the do_gzip variable).

The Note that says it's enabled by default in Varnish 4.0 should probably also be expanded to mention that only the "being compression aware" is enabled by default, not actually doing compression as that still requires enabling do_gzip.

**Comment by franciscovg** [comment]
Description improved in commit fe35ba8.
