### ISSUE TITLE
VCL variable table out of sync with text

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#104]
In section 7.8 about "Variables in VCL subroutines".

- There's a reference to a State column, which does not exist.
- There's a reference to "The _variables_ columns", specifically with variables in italics indicating that it would be somehow listed in the table. But there is no variables headline in the table.
- The sentence appearing as fourth paragraph is hanging all on it's own. The discussion about globally accessible variables should be moved to it's own paragraph. Or perhaps it should actually be made into a subsection 7.8.1?
- The language in the paragraph starting with "Remember that changes" reads quite strangely, and might need a larger rewording.

**Comment by franciscovg** [comment]
Improvement in commit df323d09499cf726311ee2c8ac9e854afe7a3c71.  Thank you for bringing up this issue.
