### ISSUE TITLE
systemd instructions for debian/ubuntu

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#105]
systemd instructions for ubuntu/debian says one should copy the unit file over from /lib/systemd/system/.

My understanding is that the correct way these days is to use an override file (in /etc/systemd/system/varnish.service.d/local.conf for example) and put the changes there, to avoid having to deal with changes if upstream makes one.

Ref: https://www.freedesktop.org/software/systemd/man/systemd.unit.html

Note! I definitely don't want to get into a long discussion about whatever the correct systemd way is :) If that's still an "open discussion point", then let's take that discussion elsewhere and just close this issue without changes. But if it is generally seen that this is the correct way, then we should be promoting that one.

**Comment by Dridi** [comment]
I personally think that we should keep sysvinit and systemd documentation to a bare minimum, and only document where to change the configuration for the packages we support (eg. /etc/sysconfig/varnish vs /etc/default/varnish)

**Comment by fgsch** [comment]
@mhagander, you are correct and this is documented in master at https://varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html. 

I agree with @Dridi re hiding the nitty-gritty details though.

**Comment by franciscovg** [comment]
Done in commit d8e42dcdbfbbff3076b0118d30b9f0f6f415c798. Thank you for the discussion.

**Comment by franciscovg** [comment]
and commit 704c16b8b36939b9cab3e6d7d6be8a9c5ad04807
