### ISSUE TITLE
The version and copyright info links to a 404 page.

### ISSUE THREAD

**Issue by dbeckham** [varnish/Varnish-Book#111]
The [version info (colophon)](http://book.varnish-software.com/4.0/#version-and-copyright) in the book references the URL http://www.varnish-software.com/book/, which returns a 404, but the actual HTML book is located at http://book.varnish-software.com/4.0/.

I believe this is the file that has the bad link: https://github.com/varnish/Varnish-Book/blob/2e83eee6ff6d33ad6c4adb92f6beac77769fad2d/util/version.sh

**Comment by franciscovg** [comment]
You are right, @dbeckham . Issue fixed in commit 5f4fd966199319b64f84733e03de7a8c4a4f54d8.

Thank you.
