### ISSUE TITLE
Title page has no following blank page

### ISSUE THREAD

**Issue by rezan** [varnish/Varnish-Book#112]
The title page is counted as page 1, and there is no blank after it, leading to the pages being off by 1 and the footer logo being on the insides rather than the outsides.

When printing the book, the title page goes on card stock and nothing is printed on the back cover. When you open the book, page 2 is the front of the first page you see. This causes all the pages to be off by 1 because the first page should be odd numbered, in this case it should be page 3 (or page 1).

If we insert a blank page after the title (back cover), then the page numbers will be aligned properly.

Other options?

**Comment by Dridi** [comment]
I think it depends mostly on who does the printing, It has never been a problem for me.

**Comment by rezan** [comment]
@Dridi What gets printed on the backside of the cover? The frontend VCL flow diagram?

**Comment by Dridi** [comment]
Nothing, we always get the diagrams on regular pages, not on the cover. Also the first diagram should be the simplified one, not the frontend. You may be losing one more page if you see the client side first.

**Comment by rezan** [comment]
This is exactly the problem, the pages are laid out in a way where the first diagram needs to be printed on the back of the cover to keep the logo alignment correct. If you do as you stated, print the first diagram on the first page, you are now off by 1 because the diagram is technically page 2.

I will leave this open for a bit longer before recommending the fix.

**Comment by Dridi** [comment]
Not sure to follow, but as far as I can remember I always ended up with a correct book, printed from various locations. If a blank page can solve your printing problem, then let's go for that.

**Comment by franciscovg** [comment]
The same here. There is no blank page problems when sending the book to print as the PDF is produced today.

**Comment by franciscovg** [comment]
@rezan , did you clarify or identify a wrong page distribution after the photos I sent you?

**Comment by rezan** [comment]
So the problem on my end is that the first diagram needed to be on the back of the front cover. I guess that was never done when I printed these books. Im ok with this now that I know this is the case.
