### ISSUE TITLE
Confusion regarding gzip and Vary?

### ISSUE THREAD

**Issue by daghf** [varnish/Varnish-Book#113]
In section 4.1 where we discuss hash keys and how different objects can have the same hash key, the following section is found:

<pre>
HTTP specifies that multiple objects can be served from the same URL, depending on the
preferences of the client. For instance, content in gzip format is sent only to clients that
indicate gzip support. Varnish stores various objects under one key. Upon a client request,
Varnish selects the object that matches the client preferences.
</pre>

This seems to give the impression that Varnish actually stores separate objects for gzipped and uncompressed objects. This used to be the case pre-3.0, but since then Varnish has had gzip support built in and is only storing the single gzipped object and gunzips on the fly for clients in need for that.

**Comment by franciscovg** [comment]
Fixed in commit eed9e179e34c04eace269526f0b9eeb54bcad10f.

Thank you for spotting the issue, Dag.
