### ISSUE TITLE
Possible improvement for exercise 9.5

### ISSUE THREAD

**Issue by FGM** [varnish/Varnish-Book#118]
The proposed solution for 9.5 (bans), while it works (skipping the need for an ACL or handling requests without all or part of the X-Ban-* headers), seems like it could be improved:

* in vcl_backend_response, it sets a x-host like the x-url
* in vcl_deliver, it removes it like the x-url

However, unlike the url, the host header appears to always be present on beresp, so there would be no point in adding a x-host: using the host is sufficient. Of course, this means the ban part is also on obj.http.host, not obj.http.x-host.

Wouldn't this be cleaner for an example solution ?

**Comment by gquintard** [comment]
The host header is a request header and has no particular reason to be present in beresp. Try curling google.com, you'll see no such header.

**Comment by FGM** [comment]
Ah, thanks for the answer. All the backends I had tried included it, so I erroneously thought it was always true. Change would not be appropriate then.
