### ISSUE TITLE
Bringing VCLExamples into the book

### ISSUE THREAD

**Issue by huayra** [varnish/Varnish-Book#30]
While having a chat on IRC a request, that makes a lot of sense, came from a reader of the book:

varnish user: ruben_varnish: indeed. There's a VCL examples that should be more promoted too
varnish user: there're valuable snippets there
varnish user: for example, the one that fixes the Vary: User-agent
...
varnish user: bring the VCLExamples to the book
varnish user: but revise them
varnish user: they're not standardized
varnish user: there're different approaches of doing the same thing

There you have something to include in the next version of it.

**Comment by franciscovg** [comment]
To do:

- Review examples in https://www.varnish-cache.org/trac/wiki/VCLExamples
- Evaluate and confirm with instructors the examples that are *very* relevant.
- Add relevant examples to the book.

**Comment by Dridi** [comment]
Most examples are either outdated or not generic enough, making it irrelevant for training material. I will now close this ticket but feel free to reopen it after cleaning up the wiki.
