### ISSUE TITLE
Lacks coverage of gzip

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#34]
There is no coverage at all in the course about the gzip functionality in Varnish 3. Yet, this is something I run into quite often with clients who consider it a very useful feature in Varnish. It's also pretty simple - but it should warrant at least a small section with some best practices and how to set it up, etc.

**Comment by franciscovg** [comment]
Considering to add section and include information from https://www.varnish-cache.org/docs/trunk/users-guide/compression.html

**Comment by Dridi** [comment]
I agree, since I also often end up explaining how it works. However, this question often show up in the HTTP chapter, at which point we don't know VCL yet.

Where would we add it?

It could be in the chapter "Saving a Request", as in "saving space for more objects" :)

**Comment by franciscovg** [comment]
https://www.varnish-cache.org/docs/trunk/phk/gzip.html

**Comment by franciscovg** [comment]
We want compressed files in the cache. Avoid compressing compressed files, such as JPEG files.

**Comment by franciscovg** [comment]
Described in fe35ba8.
