### ISSUE TITLE
Exercise for health probes/grace/saint

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#37]
This should really be an exercise and not a demo. I've usually turned it into an exercise, and it's a much better way to gain actual understanding of how grace really works - which can be tricky wen you're new to it.

**Comment by franciscovg** [comment]
This request is still relevant for the Saving a Request chapter of the Varnish-Book-v4 branch.

**Comment by Dridi** [comment]
I like the idea of the demo, because it usually saves time. I haven't had understanding issues from trainees, but I don't mind an exercise. Please remember that the current Varnish-Book-v4 exceeds the 2 days budget on both courses.

**Comment by Dridi** [comment]
Recipe for a heath probe demo:

First we need a probe, I recommend a 1 or 2 seconds interval: `.probe = { .interval = 1s; }
Then we need two terminals, one  in which we start or stop the backend, and one we project on screen to the trainees.

We can do an animated probe demo on screen like this: `watch -n.5 "varnishadm debug.health"`

While you are projecting, you can show in real time the effects of the probe results when you start/stop the backend. An easy way to bring up a backend is to run `python -m SimpleHTTPServer [port]`. This is usually enough to make the trainees understand how probes work.

Regarding grace and saint mode, the former is already covered by at least one exercise and the saint mode doesn't exist anymore.

Thoughts? /cc @aondio

**Comment by aondio** [comment]
I think it's good enough.
Another way to understand how probe works is:
Declare 2/3 very simple backends in a VCL file(I would say the default one that will be used at boot).
Set up a probe(as per your suggestion).
Using varnishadm commands declare 1/2 backend as sick.
Check debug.health and backend.list

**Comment by franciscovg** [comment]
Done in commit 2c616ba
