### ISSUE TITLE
Compile error on V4.2 release

### ISSUE THREAD

**Issue by mlieshout** [varnish/Varnish-Book#38]
Hi,

I tried to compile the V4.2 release but I'm getting this error:

Couldn't include build/exercises/complete-rewrite_urls_and_headers.rst
make: *** [build/merged_book.rst] Error 2

Any idea what went wrong?

**Comment by franciscovg** [comment]
The Makefile of the Varnish-Book-v4 branch compiles at the first run. This branch will replace master soon.
