### ISSUE TITLE
Add chapter for regular expressions

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#44]

**Comment by franciscovg** [comment]
This is a course on Varnish, not regex. Regular expressions used in the book are already explained.

**Comment by fgsch** [comment]
I think a cheat sheet for regex should be added, in particular if there are exercises that depend on understanding them.

**Comment by franciscovg** [comment]
Improving my previous comment:

The regular expressions used in the book are explained. It makes the book self-contained in that matter. A regex cheat sheet would just be a reference to something that is not covered in the book.
