### ISSUE TITLE
Add exercises to Chapter 7 "VCL Basics"

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#47]

**Comment by Dridi** [comment]
Also move the `vcl_recv` and `vcl_backend_responses` exercices from chapter 8 to chapter 7.

**Comment by franciscovg** [comment]
To move the ``vcl_recv`` exercises from Chapter 8 to 7, we need to explain VCL functions, keywords, return actions and variables.

I suggest to add a different exercise to ``vcl_recv`` in Chapter 7. Something simple like:

- add a rule to pass ``/foo``, and
- add a rule to hash based on URL only.

Exercises from ``vcl_backend_responses`` are already in place.

**Comment by franciscovg** [comment]
Done in commit 90d7019.

I did not add the suggested exercise using ``hash_data()``, because such functions should be first introduced.
