### ISSUE TITLE
CentOS 7 as main testbed for Varnish Plus

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#56]
The Varnish Plus repository log shows that RedHat users are about double than Ubuntu/Debian users. Therefore, the book should prioritise explanations and commands for RedHat instead of Ubuntu.

**Comment by Dridi** [comment]
I don't think repository logs to be an accurate metric. Especially with RHEL users, they might use a Satellite repo manager that could aggressively look for updates for mirroring.

Being myself in favour of RHEL/CentOS, I'd rather survey our customers if we want to align with their needs. Beware though, Debian being seen as "pure" or "cool", you'd switch from that to the "evil" enterprise distribution :smiling_imp:.

However, even if we switch to CentOS for our labs, it's probably still too early to go with CentOS 7. We don't want to burden trainees with systemd, that is still relatively low in terms of adoption. Even with its (partial) sysvinit support, RHEL6 users tend to stay on RHEL6 are most of them are probably still ignoring or studying systemd.

If we were to accommodate *my* tastes, I'd go with CentOS 7 :)

**Comment by fgsch** [comment]
I don't really have a strong opinion on this but I think we should have in the book *only* one distribution and point the user in the right direction (e.g. repository details are available on subscription).

There is little to no value IMO to describe every possible scenario, and this information would be available for our customers.

**Comment by franciscovg** [comment]
This ticket is to be reopen when another OS becomes a real need.

I'm closing this issue without changing the testbed because Ubuntu has proved to be good enough for the trainees we've had so far.
