### ISSUE TITLE
Installation of required software **as exercise**

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#58]
To complete the course, trainees need to the following software:

   - Varnish Cache 4.x or Varnish Cache Plus 4.x
   - Apache/2.4 or later
   - HTTPie 0.8.0 or later
   - PHP 5.4 or later
   - curl - command line tool for transferring data with URL syntax

Trainees receive access to a VM without this software preinstalled. The book explains step by step how to install and configure them. An advantage of this approach is to spend as less time as possible to get started.

@Dridi commented that it would be useful to have the installation process as an exercise to gauge the trainees.

Please comment if you have a strong opinion.

**Comment by fgsch** [comment]
Personally I think anything but Varnish should be installed. I'd say that the examples should be in the machine as well to avoid wasting time. Perhaps the exception to some of this is the developers course, but for admins I think it's pretty much pointless.

This helps focusing on Varnish and leave trifle things out of the picture.

**Comment by huayra** [comment]
@fgsch +1: This is a Varnish VCL course, not a general web perf learning session.

If you don't know your way around your web server, you should probably not be in the course yet?

On that note, we should probably be clearer about the required prior knowledge to the course the attendees should have. 

Has the lack of pre-required knowledge by the ateendess been a challenge for trainers before?

**Comment by mhagander** [comment]
I agree, but one piece of info that might be worth adding - I come across more and more people  both in this training and in other, who do *not* know Apache. They certainly know webservers (either nginx or IIS for example). I don't think I've run into explicit issues with the Varnish training on that, but I definitely have with other OSS trainings that are using Apache as examples (for example Puppet courses).

Having the webserver preinstalled *and* preconfigured would definitely help those people to focus on the parts that are actually important (Varnish+VCL).

I haven't actually looked things like exercises if they are updated etc, but if there is something apache-specific in there it might be worthwhile looking at generalizing them if possible, for those who don't know apache.

**Comment by fgsch** [comment]
@huayra only regular expressions so far.

**Comment by tfheen** [comment]
]] Magnus Hagander 

> Having the webserver preinstalled and preconfigured would definitely help those people to focus on the parts that are actually important (Varnish+VCL).

I agree on this, faffing around with installing and setting up Apache
isn't useful.  Just drop something preinstalled and preconfigured in.

You want to get going with the Varnish bits as quickly as possible, all
kinds of fighting with terminals, editors, etc is overhead that means
less learning in the allocated time.

People showing up without knowing the basics were certainly a problem in
the past, I don't know if that's improved lately.  In some cases, you'd
get people who absolutely did not know how to drive an editor, for
instance.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by Dridi** [comment]
We still need to have this "overhead" in the Varnish Book, because we need a walk-through for customers that insist on hosting the training and providing the lab environments. Other than that I agree that we should provide pre-installed environments and a note saying you can "skip this part" if the instructor said so.

My point was mainly to keep the Varnish installation as an exercise. Because the average trainee attitude will change when facing an exercise, I find it useful to watch them do it and gauge their levels.

**Comment by franciscovg** [comment]
- I will also redesign the slides for installing Varnish and Apache.
- Location of configuration files is shown too early.
- Add ``varnishd -V`` to double check that trainees have installed the version they want.

**Comment by franciscovg** [comment]
Installing Varnish and Apache are exercises with provided solutions in commit 594bf37.
