### ISSUE TITLE
Supported platforms need to be uniform

### ISSUE THREAD

**Issue by huayra** [varnish/Varnish-Book#60]
In chapter 1 there are two places where we mention supported platforms(1.1 and 1.2). The reason for this is that one mentions support for Varnish Plus while the other talks about Varnish Cache.

Listings for both Varnish Plus and Varnish Cache should be under 1.2 as we do the comparison between these in that chapter anyway, so having that also there should make sense.

I can send a pull request if you agree with my idea here.

**Comment by Dridi** [comment]
I have no strong opinion on the matter, but I think it makes sense.
:+1:

**Comment by fgsch** [comment]
fwiw, I have some related comments on this that I'm putting in an email to Francisco.

**Comment by franciscovg** [comment]
I have added a comparison table. See commit 20cb1abc7f6b6553a6580f26a1acf2686c0acaa4.

**Comment by huayra** [comment]
@franciscovg please update the table with the latest version before closing this issue.

**Comment by franciscovg** [comment]
Updated in commit 629458b
