### ISSUE TITLE
Incorrect built-in functions list

### ISSUE THREAD

**Issue by fgsch** [varnish/Varnish-Book#61]
call, set, unset and return are not functions but keywords and should not be listed under  **VCL built-in functions**.

**Comment by franciscovg** [comment]
``call``, ``set``, ``unset`` and ``return`` cause Varnish to perform specific actions, therefore they are not keywords, but **instructions**. I agree that they are not functions.

Text updated in commit c4d2b8f

**Comment by fgsch** [comment]
This is what is called keywords in any other language.

IMO there is no need to create another naming.

**Comment by franciscovg** [comment]
I checked the definition of instruction in book The Art of Computer Programming by Knuth D. I think the word *keyword* can be confusing because it can represent commands, parameters or reserved names.

**Comment by fgsch** [comment]
That's actually the case. You cannot use those in parameters and you cannot create variables called after any of them.

**Comment by franciscovg** [comment]
In the book we say that ``action`` in ``return(action)`` is a keyword. I think it is important to differentiate their type. Otherwise, we are saying that the keyword ``return`` has the keyword ``action`` as argument.

**Comment by fgsch** [comment]
Why? actions are keywords as well. `return` is probably the most universal keyword of all.

You are creating an issue where there is none.

**Comment by Dridi** [comment]
I agree with @fgsch, keyword is a good fit that probably anyone would understand in both contexts. By the way, a keyword doesn't have to be a reserved word too, it's just the case most of the time.

**Comment by franciscovg** [comment]
Ok, I see that *keyword* is the appropriate term here. Text updated in 22a64af. Thanks for the discussion.
