### ISSUE TITLE
Epub support

### ISSUE THREAD

**Issue by hugocruz** [varnish/Varnish-Book#62]
I think providing an option for epub, would be really useful because generating an epub form a pdf file is really hard to get right, and after all we have the source :)
I've played a bit with the Makefile and  was able to get it working. I don't have that much experience with sphinx so this was a bit trial and error. 
I've looked into sphinx a bit, and when generating the conf-py.in (Varnish Book documentation build configuration file) we have the option in sphinx-quickstart to enable the epub support

 ```
Sphinx can also add configuration for epub output:
 Do you want to use the epub builder (y/n) [n]: y
```
Enabling this, would be enough from what I've checked. 

Without doing this I was still able to make it work just by changing a bit the make file, and copying bit from the sphinx task. 
```
epub: ${common} src/conf.py
	for a in ui util/* vcl material build/version.rst ; do \
		if [ ! -e src/$$a ]; then \
			ln -s ${PWD}/$$a src/$$a ;\
		fi; \
	done;

#This loop should be improved! This clears out frontpage.rst and printheaders.rst and creates wrong pdf later.
	for a in src/util/frontpage.rst src/util/printheaders.rst; do \
		rm $$a; \
		touch $$a; \
	done

#Splits chapters into individual files, and creates the index page for sphinx.
	mkdir -p src/build/chapters
	ln -sf ${PWD}/ui build/chapters/

#update references in tables:
	mkdir -p src/build/chapters/tables
	for a in tables/*; do \
		util/rst2sphinxparser_tables.awk -v dst="src/build/chapters/"$$a < ${PWD}/$$a; \
	done

	util/rst2sphinxparser.igawk -v dst=${PWD}/src/ < ${mergedrst}

#Removes '.. class:: handout' from src/*.rst
	sed -i 's/\.\. class:: handout//' src/*.rst

	sphinx-build -b epub -d build/doctrees   src/ build/epub

```

this was obviously a rip off from the sphinx task, but I only wanted to test if it worked. 
Actually the only difference is the line: 
```
 sphinx-build -b epub -d build/doctrees   src/ build/epub
```
I was able to create a epub with this.

**Comment by Dridi** [comment]
Sounds fairly easy to integrate! But the build system should really be improved first...

**Comment by hugocruz** [comment]
@Dridi Yes. I will chat a bit with Francisco about that. epub/mobi, are quite helpful.

**Comment by franciscovg** [comment]
Support added in commit 762cd06
