### ISSUE TITLE
NEWS file is empty

### ISSUE THREAD

**Issue by KristianLyng** [varnish/Varnish-Book#65]
This file was there for a reason, to allow instructors to have a single reliable source they could go to to figure out what has changed as it pertains to their work. It is not the same as a git log. 

By removing it, instructors are essentially forced to either re-read the entire book for every release, or read every single git commit if they want to be properly prepared. Neither is really realistic, so the result will be instructors reading the new content in the middle of a class.

**Comment by franciscovg** [comment]
File back in commit bf365ba494846a37a2e9378e178a085512efba7c
