### ISSUE TITLE
Use ``varnishtest`` as testbed throughout the book

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#71]
``varnishtest`` is extremely powerful.  Using ``varnishtest`` as testbed will make aware all readers and trainees about this tool and they will learn its usefulness, which at the moment is rather hidden.  With ``varnishtest`` one can test all configurations and VCL programs necessary to learn Varnish without introducing dependencies, like Apache, CGI or PHP. Using ``varnishtest`` as testbed in the book is an excellent way to explain ``varnishtest`` in so many different ways.

Also, readers and trainees will realise that ``varnishtest`` is very useful not only for development of VMODs, but also as a tool for designing their VCL programs, or "just" as users (web developers) when trying to understand how Varnish works, and when integrating their web applications with Varnish.

**Comment by Dridi** [comment]
As a big fan of `varnishtest`, let me answer this with a big fat **HELL NO** :no_good: 

For a training course that could be aimed at absolute Varnish beginners, I believe it would best to avoid an abstraction like `varnishtest`. Some details are hidden behind the scenes and between that or the hassle of external dependencies and the risk of unfamiliarity, I'd pick the dependency hell.

I think it's best to run Varnish along real production-like backends, and use real production-like user agents such as curl or a web browser. I believe it to be more effective when learning Varnish to avoid abstracting its surrounding environment. And to mitigate the dependency hassle on certain platforms **cough** el5 **couch** I'd be conservative and pick curl over httpie, apache httpd over nginx and so on.

Now if it were an advanced course, I would totally have a first chapter on `varnishtest` and start the course with a strong statement that we don't care much about clients and backends, or the "vcl 4.0" thing, or even the backends declaration: we focus on Varnish. And for that, `varnishtest` is probably the best tool, but you'd need to master the fundamentals first.

My €0.02

**Comment by perbu** [comment]
The important bits are in the implementation.  I agree we shouldn't replace PHP as it is in the book today. As Dridi says, we should have something close to the trainee prod environment. We could talk about replacing it, but probably not with varnishtest. If dependencies is a problem having a built in forking CGI webserver in the book itself with no external dependencies could be a solution. Or a statically compiled all-in-one binary available on a memory stick. Dependency issues don't need to be big issues as long as 

However, back to varnishtest. I believe varnishtest has a role in the book. There are some good reasons to do this.

1) verify the syntax and semantics of the VCL examples. Each VCL examples might have an test-case or two associated with it. We've had tons of errors in the VCL in the book before and it doesn't look good.

2) Having the trainees aware of the tool is all in all a good thing as long as the tool is well documented enough the can pick it up later. Most trainees will probably not write test cases for the VCL, but those who do are golden. For these users the test cases in book would be a good examples of varnishtest to verify varnishtest semantics.

I agree we shouldn't cover varnishtest in the basic training. But if the book can cover it anyway that means we'll more people will take an interest in the book which is a good thing.

**Comment by aondio** [comment]
FYI: I'm going to rebase and push to master branch this commit from a couple of years ago https://github.com/varnish/Varnish-Cache/pull/37

**Comment by franciscovg** [comment]
I don't think that using ``varnishtest`` requires a very high level of abstraction, and I think it really helps to understand better the fundamentals of Varnish. Varnish tests cases (VTC) show very clear backends, Varnish and clients, all in one file. Reading the output of ``varnishtest`` might look intimidating for new beginners, but so is ``varnishlog``. Starting with very simple tests and building up on them should help them to realise that it is not so complicate.

Also, even if the learning curve of ``varnishtest`` is steeper for some, its payoff is also higher. So I will continue adding Varnish test cases was an alternative to current tests against Apache and other third party software. Those that don't want to teach or learn ``varnishtest``, can just skip it.

**Comment by Dridi** [comment]
We have some browser-driven exercises, which add the browser behavior to the loop. This is not something you can replace with a `varnishtest::client`, there are too many moving parts and it is not realistic to design a cache policy without taking into account actual user agents that do way more than just `txreq` and `rxresp`.

> Those that don't want to teach or learn varnishtest, can just skip it.

I insist that `varnishtest` falls into abstraction distraction. I have no problem with a mention in the basic courses, and I always do that unless we seriously run out if time. In an advanced course it's a great asset, because at this point we focus on Varnish itself and not the big picture.

**Comment by franciscovg** [comment]
@Dridi, is it OK for you if we have both, Varnish tests with VTC and tests using real clients/backends? or do you think that VTC would be very distracting in your courses?

**Comment by Dridi** [comment]
We can't have them everywhere because exercises vary a lot in different chapters. I'm not sure it'd be worth it putting test cases only in certain places. But I see the value of having test cases along the solutions, putting the VCL in context.

I'd rather put effort on an advanced course ^_^

**Comment by franciscovg** [comment]
``varnishtest`` is now explained through the book. I will continue adding VTCs when suitable.

Thank you for the discussion!
