### ISSUE TITLE
On which state is TTL written?

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#81]
The value of TTL comes either from s-maxage, max-age, or a calculation from the Expire HTTP header field. In some cases, one might want to overwrite TTL. Therefore, it is necessary to know with accuracy whether TTL will be overwritten by Varnish in a future state.

- Explain when is TTL created.

**Comment by Dridi** [comment]
I don't understand, isn't it already covered?

**Comment by aondio** [comment]
I have the same question as Dridi. I found it to be very well covered.

**Comment by franciscovg** [comment]
After discussion with Dridi, this issue is invalidated.
