### ISSUE TITLE
Explain soft purge as alternative to invalidate caches

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#84]

**Comment by Dridi** [comment]
In what regard? Both look orthogonal to me.

**Comment by franciscovg** [comment]
Soft purge https://www.varnish-cache.org/vmod/soft-purge was ment, as Dridi clarified it to me.

**Comment by franciscovg** [comment]
Done in commit 1d1600e2ddd3360a0094a189f670d9158ab61f92
