### ISSUE TITLE
List of supported platforms is outdated.

### ISSUE THREAD

**Issue by lkarsten** [varnish/Varnish-Book#89]
[14:25:33] < espen> scn: Heads up; http://book.varnish-software.com/4.0/chapters/Introduction.html lists Varnish Plus supported platforms

**Comment by franciscovg** [comment]
http://info.varnish-software.com/blog/varnish-cache-plus-supported-platforms lists platforms for the coming year. 

Where can I get the latest current supported list for Varnish Cache 4.0, Varnish Cache 4.1, Varnish Cache Plus 4.0 and Varnish Cache Plus 4.1.

Feel free to update this table directly: https://github.com/varnish/Varnish-Book/blob/master/tables/supported_platforms.csv

**Comment by franciscovg** [comment]
Table of supported platforms replaced by an external list in commit dac2e96.
