### ISSUE TITLE
Screenshots outdated

### ISSUE THREAD

**Issue by huayra** [varnish/Varnish-Book#90]
VAC screenshots are outdated. Have not checked VCS or vagent2, but they have seen new releases after the initial screenshots were added to the book.

The option would be to take out all screenshots from the book and always show a demo as part of the course (that should take 5-10 minutes), but that makes adding them to the Varnish Plus chapter pointless in the first place.

A better solution is doing this as part of the release policy of these products, which should make it impossible for the book to have outdated screenshots of the UI in it. So as part of a new release of VAC, VCS and vagent2, besides doing documentation updates, the book chapters covering them should be updated accordingly.

**Comment by franciscovg** [comment]
Product owners will update the screenshots following https://github.com/varnish/Varnish-Book/blob/master/ui/img/README.rst.
