### ISSUE TITLE
Better explanation of grace mode and bgfetch

### ISSUE THREAD

**Issue by aondio** [varnish/Varnish-Book#91]
"What happens when a subsequent request to the object is made and the bgfetch isn't completed? Will Varnish deliver the stale object until the background fetch is complete or will it busy wait for the fresh object to be available?"

The book doesn't really explains in details how Varnish behaves when grace mode is implemented.
Above a couple of questions you can't answer to just going through the book.

**Comment by Dridi** [comment]
I believe there's a limit to hand holding. You can find the answer to these questions with `varnishlog` so I'd either create an exercise for that or tell a student how to investigate his concern.

**Comment by franciscovg** [comment]
Isn't that described in https://github.com/varnish/Varnish-Book/blob/master/varnish_book.rst#waiting-state?

Also in https://github.com/varnish/Varnish-Book/blob/master/varnish_book.rst#grace-mode:

> When Varnish is in grace mode, Varnish is capable of delivering a stale object and issues an asynchronous refresh request. When possible, Varnish delivers a fresh object, otherwise Varnish builds a response from a stale object. This procedure is also known as stale-while-revalidate.
 
and  https://github.com/varnish/Varnish-Book/blob/master/varnish_book.rst#vcl-vcl-hit: 

> The background fetch is an asynchronous call that inserts a fresher requested object in the cache. Grace time is explained in the Grace Mode section."

**Comment by aondio** [comment]
Sorry, missed that.
Closing.
