### ISSUE TITLE
Move varnishtest to its own chapter

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#92]
Based on experience from class room, the current placement of ``varnishtest`` introduces confusion among students. Therefore it will be moved to its own chapter. This is to be done before the next course in San Francisco on June 14.

**Comment by franciscovg** [comment]
Done in commit 89284d6fbc0bc4b67f41b2e1e8fd49bb866034c6

**Comment by mhagander** [comment]
Commit 89284d6 references a spell check fix...

I assume you actually meant e537719 :) So just putting that one in here for future reference if somebody else is also trying to look it up.
