### ISSUE TITLE
Exercise "Filter Varnish Log Records" to use 404

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#98]
Currently, exercise 4.6 (in my numbering) which is the "Filter Varnish Log Records" exercise says to use varnishlog to print transactions for RespStatus == 503.

For students who are not doing the web dev course and do not have PHP installed for example, actually provoking a 503 error is not obvious. It would be a lot easier to instead have the exercise look for a 404 error, as those are trivial to reproduce.

Unless there is a specific reason why 503 is better?

**Comment by Dridi** [comment]
I make them stop the backend to provoke 503s, straightforward enough for sysadmins in my experience.

I have seen people figuring by themselves that they change the backend definition too.

**Comment by mhagander** [comment]
Oh, I'll admit I always thought the idea was to have the _backend_ generate the 503. Which takes more work. If it's varnish then I agree it's very straight forward.

Maybe it should be clarified for instructors like me that it's intended to be Varnish :)

**Comment by franciscovg** [comment]
Clarified in commit a65776eea887385f4e1b358a184c4cafca7ecbda.
