### ISSUE TITLE
Notable counters don't include hits/misses

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#99]
Section 4.7.1 on varnishstat has a table of notable counters. These have no mention of cache hits/misses or connections (and the difference between sessions and requests). These are certainly even more notable than the ones like losthdr, and don't fall under the category as documented "may be relevant only for Varnish developers when providing support".

It would probably also be useful to explain the MAIN.backend_\* ones, as those almost always come up in questions.

**Comment by Dridi** [comment]
I'd argue that sessions vs requests is an HTTP topic and could belong in the HTTP chapter (at this point we have already seen counters). For the rest, I have no strong feelings on which parameters are notable. What I often see is that people start with storage monitoring/plotting, and in general system counters first rather than application counters.

**Comment by mhagander** [comment]
I can definitely buy the comemnt about sessions vs request being more http.

But at least having the hitcounters etc makes a lot of sense to have in there, because that's what most people use. As are the backend_ ones. (These are the ones that are shown if you look at the dashboard in VAC for example - that in itself is a good indicator that it's a notable counter).

**Comment by franciscovg** [comment]
``MAIN.cache_hit``, ``MAIN.cache_miss``, ``MAIN.cache_hitpass``, should be there without doubt as already in VAC.

About ``MAIN.backend_*``, I suggest to add the ones below, but let me know if your training and support experience don't agree.

``MAIN.backend_req``
``MAIN.backend_conn``
``MAIN.backend_unhealthy``
``MAIN.backend_busy``
``MAIN.backend_fail``

I'm leaving out ``MAIN.backend_reuse``, ``MAIN.backend_recycle`` and ``MAIN.backend_retry``.

Should I remove ``MAIN.losthdr``?

**Comment by franciscovg** [comment]
Suggestion in commit c480a4f.

**Comment by franciscovg** [comment]
Closing since there have not been more discussion after the counters added in the commit mentioned in my previous comment.
